[theme]
primaryColor = "#1E90FF"
backgroundColor = "#0E1117"            # Dark background color
secondaryBackgroundColor = "#262730"    # Sidebar background color
textColor = "#FAFAFA"                   # Light text color
font = "sans serif"